### ISSUE TITLE
最后那个html文件怎么打开？

### ISSUE THREAD

**Issue by AnJou0** [GreatV/CloudMusic-Crawler#3]

**Comment by GreatV** [comment]
用火狐或着chrome之类的浏览器打开即可。

**Comment by AnJou0** [comment]
没有找到文件位置，请指点

**Comment by AnJou0** [comment]
![image](https://user-images.githubusercontent.com/51066155/58748541-fb7c9d00-84ac-11e9-9f53-74674eddfe48.png)

**Comment by AnJou0** [comment]
新人，麻烦您指点一下
