### ISSUE TITLE
新人，麻烦指点一下

### ISSUE THREAD

**Issue by AnJou0** [GreatV/CloudMusic-Crawler#4]
在项目执行后没找到render.html文件
![image](https://user-images.githubusercontent.com/51066155/58748597-cc1a6000-84ad-11e9-99e1-1a0dd0d1eb3e.png)
这个不知道是什么情况，修改main为__main__后可以但是找不到html文件

**Comment by AnJou0** [comment]
万分感谢

**Comment by GreatV** [comment]
你使用的python版本是什么?main函数不必修改。

**Comment by AnJou0** [comment]
python3.7.2

**Comment by GreatV** [comment]
请按照 [如何使用](https://github.com/GreatV/CloudMusic-Crawler/tree/master#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8) 再试一遍。

或者切换到 [v0.6 版](https://github.com/GreatV/CloudMusic-Crawler/tree/v0.6)

**Comment by AnJou0** [comment]
我这边虚拟环境搭建好了，但是激活时候，显示命令不对，百度的也都一样，执行不了

**Comment by GreatV** [comment]
Windows 下使用
```
venv\Scripts\activate
```
