### ISSUE TITLE
非常抱歉，再次打扰您

### ISSUE THREAD

**Issue by AnJou0** [GreatV/CloudMusic-Crawler#5]
在虚拟环境都做完之后，第一个python文件运行正常，之后第二个文件一直是说stop_words.txt有无法解码的字符，于是修改成ANSI字符，这个问题也就没有了，又报错说是，只能在POSIX System并行，我想重新启动一下，于是整个项目删掉，当我重新Dowload一份新的项目后，第一个文件又运行不了了。
![image](https://user-images.githubusercontent.com/51066155/58803984-4f20ef00-8643-11e9-93e9-9ae17b7911fd.png)
就是这个情况

**Comment by AnJou0** [comment]
请问能否分享一份运行成功的项目整体？

**Comment by GreatV** [comment]
这个可能是程序的问题，master分支还处于开发状态，没有对一些异常进行判断。你可以试试v0.6tag的代码，可能需要使用python2.7+。

**Comment by GreatV** [comment]
或者可以尝试在windows下安装一个虚拟机，然后用虚拟机安装一个linux发行版，再clone此项目到linux中运行。(推荐使用这种办法)
